M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-05-30T17:12:59+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-30T17:12:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.000
%
G90
G05
T1
X168.29Y-118.675
X168.29Y-125.675
T2
X176.0Y-51.5
X176.0Y-131.5
M30
