; ###########################################################################################################################
; PlatformIO Project Configuration File.
; It stores localized strings in PROGMEM to save RAM and provides functions to retrieve text based on the selected language.
;
; Author: CtrlAltJon
; Last Updated: January 2026
; Copyright (c) 2026 CtrlAltJon
; License: MIT
; The software is provided "as is", without warranty of any kind.
; This license notice must be included in any copy or portion of the software.
;
; ###########################################################################################################################

[platformio]
src_dir = src                                                             ; Source code directory
include_dir = include                                                     ; Header files directory

[env:d1_mini]
platform = espressif8266                                                  ; ESP8266 platform
board = d1_mini                                                           ; Wemos D1 Mini board
framework = arduino                                                       ; Arduino framework
monitor_speed = 115200                                                    ; Setting serial monitor speed (baud rate)
monitor_raw = yes                                                         ; Raw output for serial monitor
monitor_port = /dev/ttyUSB0                                               ; Serial port for serial monitor
monitor_filters = esp8266_exception_decoder, default                      ; Crash decoder for ESP8266
build_flags =
	-D USER_SETUP_LOADED=1        ; Set library to use custom setup below
	-D ST7735_DRIVER=1            ; Select driver ST7735
	-D ST7735_GREENTAB160x80=1    ; Specific configuration for 0.96" 80x160 displays
	-D TFT_WIDTH=80               ; Screen width in pixels
	-D TFT_HEIGHT=160             ; Screen height in pixels
	-D TFT_MISO=-1                ; MISO not used
	-D TFT_MOSI=13                ; D7 (MOSI - Master Out Slave In)
	-D TFT_SCLK=14                ; D5 (SCK - Serial Clock)
	-D TFT_CS=15                  ; D8 (CS - Chip Select)
	-D TFT_DC=2                   ; D4 (DC - Data/Command)
	-D TFT_RST=16                 ; D0 (GPIO 16 - Reset)
	-D TOUCH_CS=-1                ; Touch screen pin, -1 if not used to avoid warning (Touch Screen Chip Select)
	-D LOAD_GLCD=1                ; Load base font
	-D LOAD_GFXFF=1               ; Load GFX fonts (Free Fonts)
	-D LOAD_FONT2=1               ; Load font 2 (small 16px)
	-D LOAD_FONT4=1               ; Load font 4 (medium 26px)
;	-D LOAD_FONT6=1               ; Load font 6 (big 48px, alternative to Font 7)
	-D LOAD_FONT7=1               ; Load font 7 segments (used on main page for power value)
	-D SPI_FREQUENCY=40000000     ; SPI frequency (higher for more speed), maximum 40MHz for ESP8266
; -D TFT_RGB_ORDER=TFT_BGR      ; Color order (if color inverted, change into TFT_RGB), not used because the display is BGR by default
lib_deps =                      ; Library dependencies
	adafruit/Adafruit ADS1X15     ; ADC for analog sensors
	knolleary/PubSubClient        ; MQTT client for IoT communication
	bodmer/TFT_eSPI               ; TFT_eSPI library for display control
